server:
  port: 8082

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  api-docs:
    path: /resv/v3/api-docs
  swagger-ui:
    path: /resv/swagger-ui.html


spring:
  application:
    name: resv-api
  datasource:
    url: jdbc:mariadb://${DB_URL}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
#  autoconfigure:
#    exclude: io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION} # AWS_REGION 환경 변수 사용
      s3:
        bucket: eatzzy

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
