server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    register-with-eureka: true
    fetch-registry: true


spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: app-api
          uri: lb://app-api
          predicates:
            - Path=/login,/app/**
        - id: resv-api
          uri: lb://resv-api
          predicates:
            - Path=/resv/**
        - id: swagger-redirect
          uri: no://op
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RedirectTo=302, /app/swagger-ui/index.html#/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: app
        url: /app/v3/api-docs
      - name: resv
        url: /resv/v3/api-docs