apiVersion: v1
kind: Service
metadata:
  name: app-api-service-blue
spec:
  selector:
    type: backend-app
    deployment: blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
