apiVersion: v1
kind: Service
metadata:
  name: discovery-svc
  namespace: default
spec:
  selector:
    app: discovery
  ports:
    - name: http
      port: 8761
      targetPort: 8761
  type: ClusterIP
