apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
spec:
  selector:
    type: backend-discovery
  ports:
    - name: http
      port: 8001
      targetPort: 8001
  type: ClusterIP
