apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    type: backend-gateway
    deployment: blue
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
