
apiVersion: v1
kind: Service
metadata:
  name: resv-api-service-blue
spec:
  selector:
    type: backend-resv
    deployment: blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
