apiVersion: v1
kind: Service
metadata:
  name: resv-api-service
spec:
  selector:
    type: backend-resv
    deployment: blue
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
