version: 2.1

jobs:
  gradle-build:
    docker:
      - image: cimg/openjdk:17.0
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: 디버깅 - gradlew 있는지 확인
          command: |
            pwd
            cd backend
            ls -al
      - run:
          name: Add Permission
          command: chmod +x gradlew
      - run:
          name: Gradle Build for all backend modules
          command: |
            for module in app-api resv-api gateway discovery; do
              echo "🔧 Building JAR for $module"
              ./gradlew :$module:bootJar
            done
      - persist_to_workspace:
          root: .
          paths:
            - app-api/build/libs/*.jar
            - resv-api/build/libs/*.jar
            - gateway/build/libs/*.jar
            - discovery/build/libs/*.jar

  docker-build-and-push:
    docker:
      - image: cimg/base:2022.09
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/project
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build & Push all backend module images
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM

            for module in app-api resv-api gateway discovery; do
              echo "Building image for $module"
              docker build -t $DOCKERHUB_USERNAME/$module:$TAG ./$module

              echo "Pushing image for $module"
              docker push $DOCKERHUB_USERNAME/$module:$TAG
            done

workflows:
  version: 2
  build-and-push:
    jobs:
      - gradle-build
      - docker-build-and-push:
          requires:
            - gradle-build
